version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_distribution_service_app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
    command: npm run start
    env_file:
      - .env
    environment:
      - PORT=3000
      - JWT_SECRET=your_secret_json_web_token
      - MONGO_CNN=mongodb://mongo:27017/notification_distribution_service_database
      - REDIS_PORT=6379
      - REDIS_HOST=redis

  mongo:
    image: mongo:6.0.1
    container_name: notification_distribution_service_mongodb_container
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.4-alpine
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
  redis_data:
